import time
import math

doc_count = int(
    open(
        "../wikipedia-word-frequency-master/results/docs_count_minfreq3.txt", "r"
    ).read()
)
max_possible_idf = math.log(doc_count / 1)

start_time = time.time()

found = {}
for line in open(
    "../wikipedia-word-frequency-master/results/word_docs_it_minfreq3.csv", "r"
).readlines():
    word = line.split(",")[0].replace('"', "")
    if word in WORD_LIST and len(found) < len(WORD_LIST):
        docs = line.split(", {")[1]
        num_docs = docs.count(",") + 1
        idf = math.log(doc_count / num_docs)
        norm_idf = idf / max_possible_idf
        found[word] = norm_idf
# del line

log.info(found)

exec_time = time.time() - start_time
log.info("Exec time:: " + str(exec_time) + "s")

###########

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

log.info("preso :", lemmatizer.lemmatize("preso"))
log.info("corpora :", lemmatizer.lemmatize("corpora"))

#######

import spacy

words = [
    ("figliare", 0.1),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
]

nlp_it = spacy.load("it")

lemmas = []

for word_tuple in words:
    word = word_tuple[0]
    score = word_tuple[1]

    for doc in nlp_it.pipe([word]):
        if doc.is_parsed:
            for word in doc:
                lemmas.append((word.lemma_, word.pos_, score))

log.info(f"{lemmas}")

seen = set()
deduplicated_filtered_best_matches = [
    (word, pos, score)
    for word, pos, score in lemmas
    if not (word in seen or seen.add(word))
]
log.info(f"{deduplicated_filtered_best_matches}")

### STANZA

import stanza
import time
from spacy_stanza import StanzaLanguage

snlp = stanza.Pipeline(
    processors="tokenize,mwt,pos,lemma", lang="it", use_gpu=True, pos_batch_size=3000
)
nlp = StanzaLanguage(snlp)

start_time = time.time()
lemmas = []
words = [
    ("figliare", 0.1),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
    ("bambina", 0.1),
    ("ammalarsi", 0.2),
    ("bello", 0.2),
    ("bambini", 0.1),
    ("uscito", 0.3),
    ("partì", 0.4),
    ("nascita", 0.1),
    ("dipingere", 0.0),
]
log.info(len(words))

for word_tuple in words:
    word = word_tuple[0]
    score = word_tuple[1]

    for doc in nlp.pipe([word]):
        if doc.is_parsed:
            for word in doc:
                lemmas.append((word.lemma_, word.pos_, score))

log.info(f"{lemmas}, {time.time() - start_time}")

start_time = time.time()
lemmas = []
for doc in nlp.pipe([tuple[0] + "\n\n" for tuple in words]):
    if doc.is_parsed:
        for word in doc:
            lemmas.append((word.lemma_, word.pos_, 0.0))

log.info(f"{lemmas}, {time.time() - start_time}")

concatenated_words = " ".join([tuple[0] for tuple in words])
start_time = time.time()
lemmas = []
for doc in nlp.pipe(concatenated_words):
    if doc.is_parsed:
        for word in doc:
            lemmas.append((word.lemma_, word.pos_, 0.0))

log.info(f"{lemmas}, {time.time() - start_time}")


####

list = [
    (7, 13),
    (9, 11),
    (5, 9),
    (6, 7),
    (8, 7),
    (4, 5),
    (11, 5),
    (10, 4),
    (12, 4),
    (14, 4),
    (17, 4),
    (3, 3),
    (13, 3),
    (15, 3),
    (16, 3),
    (20, 3),
    (21, 2),
    (24, 2),
    (18, 1),
    (19, 1),
    (22, 1),
    (26, 1),
    (28, 1),
    (34, 1),
    (35, 1),
    (179, 1),
]

list[:3]

###

demauro = open(
    "F:\PythonProjects\\texmega_py\\resources\DeMauro2016_NVdB02_altouso.txt", "r"
).readlines()
demauro = [word.split("\t")[0] + "\n" for word in demauro if "	v." in word]
open("F:\PythonProjects\\texmega_py\\resources\demauro_verb_list.txt", "w").writelines(
    demauro
)
